### ISSUE TITLE
Support `@GQLValueType`s when rendering API

### ISSUE THREAD

**Issue by jvican** [ghostdogpr/caliban#1126]
When using the `render` method on the `GraphQL` object, Caliban prints a schema that can be distributed to clients. However, this schema contains no information about value types and instead uses the underlying representation, which loses type information. The GQL Value types could be represented as scalars in the schema, right after the `Long` and `DateTime` definitions. I'd like to suggest that Caliban supports this feature either by default, or by opting in via either of the following mechanisms:

1. A configuration option in the `render` method
2. A `GQLScalarType` annotation that combines the semantics of `GQLValueType` and the scalar representation

**Comment by ghostdogpr** [comment]
The `render` function is only a reflection of the schema, so in order to change the generated GraphQL type, the `Schema` must be changed as well (so the type will be consistent in `render`, in introspection and when validating queries).

You can achieve this today with for example:
```scala
case class MyScalar(value: Int)

implicit val myScalarSchema: Schema[Any, MyScalar] = Schema.scalarSchema("MyScalar", None, IntValue(_))
```
Your second suggestion would work. To prevent breaking existing code, we could re-use `GQLValueType` but add a parameter `isScalar: Boolean = false` to turn on this behavior:
```scala
@GQLValueType(isScalar = true)
case class MyScalar(value: Int)
```
Does that sounds like what you wanted?

**Comment by ghostdogpr** [comment]
Turns out it was simple: https://github.com/ghostdogpr/caliban/pull/1127

**Comment by jvican** [comment]
Great! #1127 looks like what I need, thanks for the quick PR and prompt answer. Let me know when this is released as I'll use it right away. Had a brief look at the PR implementation and looks solid, nothing to add.

Your approach to customize the schema instance is something I've considered in the past but it's verbose enough for all my types that I've discarded it, the new solution to this problem is much better.

**Comment by ghostdogpr** [comment]
@jvican you're lucky, I was about to release so it made it into [1.2.2](https://github.com/ghostdogpr/caliban/releases/tag/v1.2.2)
