### ISSUE TITLE
ZIO[R, E, A] type as not nullable

### ISSUE THREAD

**Issue by fokot** [ghostdogpr/caliban#120]
This is not a bug, but enhancement. There is `ZIO[R, E, A] | Nullable A` in the docs. I think it might be useful if it `ZIO[R, E, A] ` will return `A` and not a `nullable A`. In sangria `Future[A]` is `A` and `Future[Option[A]]` is `nullable A`. Many times I use `ZIO` or `ZQuery` just to make data loading lazily. If it is not nullable and one generates `flow` or `typescript` from queries it is also easier to work with because it will not force you to check nulls.

**Comment by ghostdogpr** [comment]
You can find the original discussion about this behavior here: https://github.com/ghostdogpr/caliban/issues/76

Since the effect can fail, there is a chance to have no result. If you want to fail the whole query instead of returning null for that field (which is the default behavior), you can transform `E` into `Nothing` using `.orDie` on your effect.

**Comment by ghostdogpr** [comment]
I will add to the documentation the fact that it won't be nullable if E is `Nothing`.

**Comment by ghostdogpr** [comment]
Documentation was updated so I close this
