### ISSUE TITLE
Wrong List type derivation

### ISSUE THREAD

**Issue by fokot** [ghostdogpr/caliban#121]
`RIO[R, List[Book]]` is derived to gql type `ListBook` instead of `[Book]`
The type as two possible subtypes
```
::Book
Nil
```

Example is here
https://github.com/fokot/caliban-example/commit/43bf1efbf8ddf4a194837a027fd88cfefe08ff3b
You can find it in http://localhost:8000/graphiql

Sorry I was not able to minimise it. If it is the only mutation the error is still there. When I remove `BookId =>` the error disappeared

**Comment by ghostdogpr** [comment]
Yeah, you ran into the case that I described [here](https://ghostdogpr.github.io/caliban/docs/schema.html) in the Warning section. Your type `Book` is used in multiple places and is recursive, so Magnolia has trouble with it.

You need to add `implicit lazy val bookSchema = gen[Book]` then it's working well. Note the `lazy` because the type is recursive (it contains `Author` which can contain `Book`). I plan to add it to the [FAQ](https://github.com/ghostdogpr/caliban/issues/67) at some point.

**Comment by fokot** [comment]
Yes it worked. Very cool! I will close this issue as there is another one dealing with the FAQ.
