### ISSUE TITLE
'Class too large' in using custom types for GQL input types

### ISSUE THREAD

**Issue by 0livia-li** [ghostdogpr/caliban#1258]
Hi!
We're using caliban version 0.9.3 and attempting to use a custom type for an input argument in a mutation. After defining the argbuilder typeclasses for the nested types that the compiler complains about, we are left with the following error: 
`Class too large`

I'm familiar with the error `Method too large` but haven't seen this before. Does this version have a limit on the number of nested fields that are allowed for a custom argument?

**Comment by ghostdogpr** [comment]
I suspect it's the same problem as "Method too large". Does it help if you add intermediate `ArgBuilder` instances for some of your types (especially any type that is used in multiple places) e.g. `implicit val myTypeArgBuilder: ArgBuilder[MyType] = ArgBuilder.gen`.

If not, I would need a reproducer in order to look at it in details.

**Comment by ghostdogpr** [comment]
Closing for now, please reopen if you have more details.
