### ISSUE TITLE
Internal compiler error when using caliban.GraphQL.graphQL

### ISSUE THREAD

**Issue by henrikurms** [ghostdogpr/caliban#1335]
Scala 3.1.1
Caliban 1.4.0

Hello, when I try to compile the following program I can an internal compiler error, at first scalac reports
```
given instance gen is declared as `inline`, but was not inlined

Try increasing `-Xmax-inlines` above 32
```
But then I get a stack trace that starts with
```
exception while typing _$3.*: of class class dotty.tools.dotc.ast.Trees$Select # -1
```
and seems to be caused by
```
java.lang.AssertionError: assertion failed: method *: in trait Tuple
```

```scala
import caliban.GraphQL.graphQL
import caliban.RootResolver

object Main {

  def graphql = (bar: Bar2) => graphQL[Any, Bar2, Unit, Unit](RootResolver(bar))
}

case class Foo(s: String, foo: List[Option[(String, String)]])
case class Foo2(foo: Foo)
case class Bar(s: String, foo: Foo2 => String)
case class Bar2(bar: Bar)
```

I have also created a repo with the code [here](https://github.com/henrikurms/scala3caliban-issue)

**Comment by ghostdogpr** [comment]
Related issue: https://github.com/lampepfl/dotty/issues/13044

There are 2 problems here: when the generated code is too long, the inline generated code is too long, which is why it asks for increasing `-Xmax-inlines`. A better way to solve that is to explicitly create an instance of `Schema` by calling `Schema.gen` for some intermediate type (to split the generated code into smaller bits):
```scala
implicit val fooSchema: Schema[Any, Foo] = Schema.gen
```
The other problem is that you use a tuple as an input type. There is no `ArgBuilder` instance for `Tuple` provided by Caliban. You need to create one:
```scala
implicit lazy val tupleArgBuilder: ArgBuilder[(String, String)] = ???
```
With this, it compiles well: https://scastie.scala-lang.org/41vwKYvcQ1a0D9CtAQL84w
