### ISSUE TITLE
Generated views do not compile if a type has more than 22 fields

### ISSUE THREAD

**Issue by kormbrek-rally** [ghostdogpr/caliban#1351]
The way views are created, if a type is more than 22 fields, the generated view (and thus the client) does not compile.

In caliban/codegen-sbt/src/sbt-test/codegen/test-compile/src/main/graphql/genview/schema.graphql, add
```
type Big {
    field0: String
    field1: String
    field2: String
    field3: String
    field4: String
    field5: String
    field6: String
    field7: String
    field8: String
    field9: String
    field10: String
    field11: String
    field12: String
    field13: String
    field14: String
    field15: String
    field16: String
    field17: String
    field18: String
    field19: String
    field20: String
    field21: String
    field22: String
    field23: String
}
```
`cd codegen-sbt/src/sbt-test/codegen/test-compile`
`sbt -Dplugin.version=1.4.0`
type in `test` and hit Enter

```
[error] /.../caliban/codegen-sbt/src/sbt-test/codegen/test-compile/target/scala-2.12/src_managed/main/caliban-codegen-sbt/genview/Client.scala:222:16: too many elements for tuple: 24, allowed: 22
[error]           case (
[error]                ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

We are likely going to restructure the data to avoid the limit of 22, but I thought this was worth reporting.

**Comment by ollyw** [comment]
In the short term, would there be any value in not generating views with more than 22, so that the generated code still compiles? If you have a project with many views, and only one has more than 22 it is a bit frustrating. The generator could just leave a comment in the generated code to say why.

Alternatively if you have an idea of what data structure is preferable, perhaps I could take a go at making the change

**Comment by ghostdogpr** [comment]
That would be a good quick fix and better than the current state!

A fix for the longer term would be to create nested tuples when there are more than 22 fields.
