### ISSUE TITLE
Consider Schema.toType to be effectful

### ISSUE THREAD

**Issue by sergeykolbasov** [ghostdogpr/caliban#1360]
There are cases when the schema could depend on the application or request-time environment.

For instance:
- running API in staging & production mode and hiding certain fields & types in production
- render different schema fields & types based on authorization

In case `Schema.toType` has a `IO[R, __Type]` return type, it would be possible to drag through that information via `R` env and affect the construction of `__Type`.

Is there a better option I've overlooked? I'm concerned that such change would be quite large & backward-incompatible.

**Comment by ghostdogpr** [comment]
Hmm I think it would be pretty bad performance-wise, because we access those types from various places during query execution. We rely heavily on cache to maximize performance, I can't really imagine if it was recalculated each time 🤔 
There might be other ways to do that. Changing the types when the API starts should already possible. Doing so per request is more tricky, maybe using wrappers.
