### ISSUE TITLE
Custom Error types

### ISSUE THREAD

**Issue by UkonnRa** [ghostdogpr/caliban#140]
Now `CalibanError` is a sealed trait and all of the messages will be decoded as a string like:
```
  "errors": [
    "Execution error: {\"@type\":\"EmailAlreadyExisted\"}"
  ]
```
But as the [GraphQL Spec says](https://graphql.github.io/graphql-spec/June2018/#sec-Errors), the recommended error looks like:
```
{
  "errors": [
    {
      "message": "Name for character with ID 1002 could not be fetched.",
      "locations": [ { "line": 6, "column": 7 } ],
      "path": [ "hero", "heroFriends", 1, "name" ],
      "extensions": {
        "code": "CAN_NOT_FETCH_BY_ID",
        "timestamp": "Fri Feb 9 14:33:09 UTC 2018"
      }
    }
  ]
}
```
And my domain error trait looks like:
```scala
sealed trait DomainError {
  val code: String Refined CodeMatcher
  val message: String Refined NonEmpty
  val statusCode: Int Refined StatusCodeMatcher
}
```

No matter what, I hope that Caliban can handle the JSONObject type, rather than put everything into a single string.

**Comment by ghostdogpr** [comment]
You can do `mapError` on your `GraphQLInterpreter` object time transform the CalibanError into your own type and unfold your domain errors. 

However looking at the Circe encoder i think this will get transformed into a string anyway so I might have to make that more flexible. I’ll have a look when I get back.

**Comment by UkonnRa** [comment]
Now I have at least two points where I **have to** transform my domain errors into `CalibanError`:

1. When write custom `ArgBuilder`s. Because:
```scala
  def flatMap[A](f: T => Either[ExecutionError, A]): ArgBuilder[A] = (input: InputValue) => self.build(input).flatMap(f)
```
2. When creating `RootResolver(queries, mutations)`, I have to ensure that all the errors in `IO` must be `CalibanError`, or the runtime exception will be thrown:
```
    "Execution error on field '<some-operator>': 
Effect failure with java.lang.ClassCastException: 
class com.xxx.DomainError$<DomainErrorType> 
cannot be cast to class
java.lang.Throwable 
(com.xxx.DomainError$<DomainErrorType> is in unnamed module of loader 'app'; java.lang.Throwable 
is in module java.base of loader 'bootstrap')"
``` 

So I have to convert my domain errors into JSON and put them into `CalibanError`, then `mapError` on `GraphQLInterpreter`, which cause meanless JSON serialization/deserialization.

So, we need to figure out how to handle this problem...

**Comment by ghostdogpr** [comment]
For 2. they don’t have to be `CalibanError`, they just have to be `Throwable`. You can simply make your domain errors extend Throwable and that should be okay.

**Comment by paulpdaniels** [comment]
I created a PR #145 which should correctly encode the message into an object instead of a string per the spec. More work will need to be done to provide the other fields. In particular the `location` and `path` field will require changes to the execution, validation and parsing stages, because we will need to 

1. Track the index location of the start of the selection field and then compute a relative line/column by re-tracking it through the original request (I think, based on the capabilities of fastparse at least).
2. We will need to pass along a path when generating the steps so that we can pass the path to the execution handler when it is building an error.

The second point would actually have further use when creating middleware such as the apollo-tracing or apollo-caching spec both of which require paths in order to build the extension body.

The last requirement of having a custom extension body would be easier to service. We could add a `def withExtension(fn: ResponseValue => ResponseValue): CalibanError` method to the `CalibanError` then add a `def extensions: ResponseValue` to the error itself.

**Comment by ghostdogpr** [comment]
Since the rest of the work can be done separately, I created 3 issues #156 #157 #158 for supporting locations, path and extensions. Closing this one.

**Comment by monksy** [comment]
Just an update to this: new custom error types are supported without being throwable via; https://github.com/ghostdogpr/caliban/pull/1059
