### ISSUE TITLE
mapN for tuples with more than 22 fields

### ISSUE THREAD

**Issue by winsvu** [ghostdogpr/caliban#1438]
**This is a caliban client question.** I am using version 2.0.1

I have a case class with more than 22 fields. This case class is a custom view. When I call the method **mapN**, it fails because there is no implementation of **mapN** with more than 22 fields. 

How can I achieve it? What should I use instead?

**Comment by ghostdogpr** [comment]
This is because Scala 2 doesn't support tuples with more than 22 fields, so it's impossible to write a `mapN` function that does `case (a, b, c, ...)` with more than 22. 
So in this case you either have to change your case class to nest some fields, or do a more manual job to group parts of your selection together e.g. `(a ~ b ~ c) ~ (d ~ e ~ f)` so that no tuple is larger than 22.
