### ISSUE TITLE
Experiment semi-auto derivation

### ISSUE THREAD

**Issue by ghostdogpr** [ghostdogpr/caliban#1579]
Automatic derivation is great when you get started but for large schemas it's more efficient to explicit call `gen` for every type. The problem is that because auto-derivation is always on, it's hard to control which types are derived automatically or not. 

We could try to remove automatic derivation and add an import for it instead.

**Comment by guizmaii** [comment]
I'd love that. I always dislike automatic derivation

**Comment by ghostdogpr** [comment]
I experimented with this a little bit, and met one problem: when using auto-derivation with an import, the instances defined in companion objects get a lower prority than the auto-derivation (because importing it gives it higher priority). It works well when using full auto derivation (everything auto-generated) or full semi-auto derivation (explicitly define all instances with `gen`), but the behavior of mixing both of them is very confusing and unpredictable.

**Comment by guizmaii** [comment]
If you ask me, auto derivation should be removed as it generates unpredictable behaviour/complicated issues.
At first, it looks like a good idea - less code to write -, but the practice demonstrated that semi-auto should be preferred.

Also, beginners will usually pick auto mode as it seems easier but will then later get bitten by too complicated-for-them issues. So, to me, removing auto mode is also helping beginners to make the correct, long-term, safe, actually easier choice.

I for example advocate to rename the `io.circe.auto._` mode to `io.circe.yolo._` mode (naming comes from Skunk IIRC which made this choice), to indicate that, yes it's magic and it's not a good thing

**Comment by frekw** [comment]
I'm super supportive of this change. I never use auto derivation for anything for the reasons @guizmaii  mentions. I think this will make debugging the weirder cases of auto derivation much easier while also decrease the frequency of new users running into "method too large"-errors.

I think another nice benefit of doing it semi automatically is that the Schema typeclass itself becomes much less magical which should make it easier for new users to apply already existing knowledge from the rest of the ecosystem to do more advanced customization.

It's a shame that moving it to an import changes the implicit resolution through since it makes the change much more disruptive (I guess the migration path is just to use semi auto and call genAll top level?). Is this an issue for other libraries that rely on auto derivation as well (I don't know because I never use auto derivation 🙂).

Regardless of the backwards compat I'm super supportive of this change because it doesn't increase the threshold to get started with Caliban by any significant amount, but will ensure that Caliban code bases scales much better with less surprises to larger schemas.

**Comment by ghostdogpr** [comment]
Yeah, I'm getting increasingly convinced that this is the way to go. The error messages you get when using the semi-auto mode are WAY better than the auto mode, and it prevents all the weird cases where you think something is used but is not.

I think it makes sense to keep the auto mode for quick prototyping and for people who really want it, with the caveats clearly exposed in the docs. I kept most of the tests with the auto mode because it's the one that needs the more tests (the semi-auto is really straightforward, it just works).

I've opened a PR that is ready for review: https://github.com/ghostdogpr/caliban/pull/1591

**Comment by ghostdogpr** [comment]
I assume we should do the same for `ArgBuilder`?

**Comment by frekw** [comment]
> I assume we should do the same for ArgBuilder?

Yeah I definitely think so! Both to keep it consistent but I think most of the same arguments hold for ArgBuilders as well! 👌

**Comment by guizmaii** [comment]
What about naming this mode with a less appealing name?

IMO, `auto` doesn't suggest the dangerousness of this mode. 
Worse, I'd argue that it's appealing to beginners: "cool there's an automatic mode that does the work for me" without knowing the risks/drawbacks. When they'll learn about these drawbacks, it'll be too late, their codebase will be hard to refactor, and their bosses will not give them time to refactor (no value for the customers, so will always be reported to later)

What about `yolo` (to follow Skunk idea), or `darkMagic`, or something else? Open to suggestions :)

I've seen too many fragile codebases because they were using the auto mode of Circe and it was really hard  to refactor/change because of a lack of proper testing: so hard that no one could justify the risks and costs to the business so it was never refactored

**Comment by Fluxx** [comment]
Just wanted to chime in to add to the support for this. I help support a lot of other engineers with their schemas at our company, and automatic derivation is certainly nice but really complicates things beyond basic examples. People get somewhat cryptic compilation error or weird schemas and are a loss as to what to do.

We also make heavy use of Thrift types internally, and our thrift compiler generates Scala code for Thrift enums that can get picked up by automatic derivation, but produces a very undesirable schema. We have internal tooling and helpers to generate manual schemas for those Thrift enums, but people routinely run into problems where automatic derivation overrides those manual schemas (I in fact helped one person with this today). So being able to control when automatic derivation happens would be very helpful.

**Comment by ghostdogpr** [comment]
I am not a fan of the "weird" or scary names, I prefer to be very clear in the docs about the tradeoffs and let the users decide. In some case I think auto can be fine.
In any case I am quite convinced by the prototype I've done so I will finish it, apply it to `ArgBuilder` as well and include that in the next 2.1 release (together with the adapters refactor that allows choosing the json library much more easily). Better to include all breaking changes at once.

**Comment by ghostdogpr** [comment]
The PR is now ready for anyone who wants to try it: https://github.com/ghostdogpr/caliban/pull/1591
It includes support for the `derives` keyword in Scala 3, which makes it super nice and easy to derive schemas.
