### ISSUE TITLE
Interpreter hangs when using enums with the same name

### ISSUE THREAD

**Issue by DGolubets** [ghostdogpr/caliban#2342]
I have a type with 2 enums within:
```
case class Type1(
  payload1: ZQuery[Any, Throwable, Option[PayloadEnum1]],
  payload2: ZQuery[Any, Throwable, Option[PayloadEnum2]],
)
```
PayloadEnum1 and PayloadEnum2 have members with the same names.
The code happily compiles but then hangs.
Solved by renaming enum members.

**Comment by paulpdaniels** [comment]
Could you include a minimum reproducer? Then we can look into it.

**Comment by DGolubets** [comment]
> Could you include a minimum reproducer? Then we can look into it.

Sure: https://gist.github.com/DGolubets/66f8ae9aac9d5ec0a44222d24f946dcc

While making it, I realized it only happens when bootstrapped with Zio http like this.
It works correctly with `unsafe.runServer`.

**Comment by kyri-petrou** [comment]
> While making it, I realized it only happens when bootstrapped with Zio http like this.
It works correctly with unsafe.runServer.

@DGolubets Honestly, thank you for figuring this out, you saved me _a lot_ of hours of debugging 🙏.

The issue seems to be a really bad manifestation of https://github.com/zio/zio-http/issues/2961. I tried the repro above using the latest snapshot version of `zio-http` ([3.0.0-RC9+8-df1523e4-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/dev/zio/zio-http_2.13/3.0.0-RC9+8-df1523e4-SNAPSHOT/)) and it seems to fix this issue.

Can you try as well and let me know if it works for you too?

**Comment by DGolubets** [comment]
> @DGolubets Honestly, thank you for figuring this out, you saved me _a lot_ of hours of debugging 🙏.

Glad I could help a bit :)

> Can you try as well and let me know if it works for you too?

It works for me too. Thank you!
