### ISSUE TITLE
Supporting ws (not wss) for development

### ISSUE THREAD

**Issue by mitsutaka-takeda** [ghostdogpr/caliban#354]
Hi. I wanted to use ws request for local development with a tool like [postwoman](https://github.com/liyasthomas/postwoman), but a connection failed because response from a server always include 'Sec-WebSocket-Protocol' header.

https://github.com/ghostdogpr/caliban/blob/2c760400a0273b38444d28c2915859edc016d887/adapters/http4s/src/main/scala/caliban/Http4sAdapter.scala#L233

This header in response should match the header in request. If I change the code to check the header and conditionally includes the header, the connection succeeds.

```scala
   // in caliban.Http4sAdapter#makeWebSocketService
    val wssHeader = CaseInsensitiveString("Sec-WebSocket-Protocol")

    HttpRoutes.of[RIO[R, *]] {
      case r@(GET -> Root) =>
        for {
          sendQueue <- fs2.concurrent.Queue.unbounded[Task, WebSocketFrame]
          subscriptions <- Ref.make(Map.empty[Option[String], Fiber[Throwable, Unit]])
          builder <- WebSocketBuilder[RIO[R, *]].build(
            sendQueue.dequeue,
            processMessage(sendQueue, subscriptions),
            headers = r.headers.get(wssHeader).fold(Headers.empty)(_ => Headers.of(Header(wssHeader.toString(), "graphql-ws"))),
            onClose = subscriptions.get.flatMap(m => IO.foreach(m.values)(_.interrupt).unit)
          )
        } yield builder
    }
```

**Comment by ghostdogpr** [comment]
Hi! First time I hear about postwoman, nice alternative to postman 😄 

The thing is, this WS adapter implements the `graphql-ws` protocol so I think it makes sense to use this header. If we wanted to be 100% correct, we should actually reject client queries if they don't have this header. Or we could just be more permissive as you suggest.

As far as I can see, postwoman doesn't support subscriptions for GraphQL, so you were trying to use the "Realtime" tab and send the packets yourself? I personally use [Altair](https://altair.sirmuel.design/) as a testing client since it supports the `graphql-ws` protocol which is quite convenient. It's not web-based though.

**Comment by mitsutaka-takeda** [comment]
Yes, I'm using the "Realtime" tab. I didn't know about the graphql-ws protocol.

> As far as I can see, postwoman doesn't support subscriptions for GraphQL, so you were trying to use the "Realtime" tab and send the packets yourself?

I just tried Altair, and its working and looks really good! I will close this issue. Thanks!

**Comment by imolorhe** [comment]
Hey, just to add my two cents. Altair is web-based, but also has browser extensions and desktop apps 🙂 If you don't want to install anything, you can just use the [online version](https://altair-gql.sirmuel.design/).

**Comment by ghostdogpr** [comment]
@imolorhe oh that's cool, I didn't know. I am a big fan of Altair, this is my main tool for testing Caliban and I always recommend it. Thanks a lot for your work! 🙏

**Comment by imolorhe** [comment]
Nice! I'm glad to hear that Altair has been very useful!
