### ISSUE TITLE
Proper way to clean resources on websocket closure

### ISSUE THREAD

**Issue by antosha417** [ghostdogpr/caliban#365]
Hi! 
In [examples](https://github.com/ghostdogpr/caliban/blob/0f2e4d5465942f00c6164aa906ccd83f70385474/examples/src/main/scala/caliban/ExampleService.scala#L67) there is a queue creation on every subscription.
Why is it not possible to clean such resources on websocket closure? 
It seems that the only way is to call `queue.shutdown` explicitly when it gets too big. 
Thank you in advance!

**Comment by ghostdogpr** [comment]
@antosha417 Hi! You're right, the queues created in `examples` were staying there forever. I had this logic:
```scala
queue
                    .offer(name)
                    .onInterrupt(
                      subscribers.update(_.filterNot(_ == queue))
                    ) // if queue was shutdown, remove from subscribers
```
but the queue was never shutdown, so it was never removed from `subscribers`.
I fixed it in this commit: https://github.com/ghostdogpr/caliban/commit/7a276759c4ccaada6486ad0df02cd2f8d8d72f25

This will shutdown the queue when we interrupt the stream (which happens if we unsubscribe or close the WebSocket). That way, it will be removed from `subscribers` as well.
