### ISSUE TITLE
Cats Effect instead of ZIO?

### ISSUE THREAD

**Issue by domasx2** [ghostdogpr/caliban#37]
Hi,

Any particular reason to stick to ZIO instead of using Cats Effect?
This looks exactly what we need, but we went with Monix, which makes integration a bit more complicated...

**Comment by ghostdogpr** [comment]
I chose ZIO over Cats Effect because it supports explicit errors (no bifunctor in CE), environment and streams, as well as the overall simplicity of a concrete effect type over tagless final.

But it is completely possible that you wrap the main call (`execute`) the same way you wrap a `Future`, and you can write an instance of `Schema` for Monix `Task`. As long as you don't mind having both libraries in your classpath (ZIO and Monix), this is totally doable.

If there is interest, I can imagine having a caliban-cats or caliban-monix that does the wrapping work and provide what's needed.

**Comment by domasx2** [comment]
Alright, I intend to give this a go next time we need a scala graphql microservice and see how it goes :) Thanks for the cool lib

**Comment by hepin1989** [comment]
When handling GraphQL's ExecutionResult/IO[ExecutionResult]， ZIO  feet more

**Comment by hejfelix** [comment]
+1 for caliban-cats. :)

**Comment by ghostdogpr** [comment]
Merged 2 related PRs:
- #53 allows using the `GraphQL` class with cats-effect `F` instead of ZIO
- #56 allows using `Http4sAdapter` with cats-effect `F` instead of ZIO

What's missing:
- add an instance of `Schema` for `F`
- add a documentation page that summarizes all of it and show a full example using Cats IO or Monix

**Comment by ghostdogpr** [comment]
Released 0.1.1 with the cats interop module. Happy people can thank @desbo 😄
