### ISSUE TITLE
Modelling computed fields depending on parent

### ISSUE THREAD

**Issue by fokot** [ghostdogpr/caliban#39]
I used this a lot in sangria gql api. In your example I would like to return `CharacterDetail`s instead of `Character`s. I do not want to calculate statistics everytime only when they are queried, that's why I model this field as a `Task` and not an `Int`.
``` 
case class CharacterDetail(name: String, nicknames: List[String], origin: Origin, role: Option[Role], statistics: Task[Int])

  object CharacterDetail {
    def apply(c: Character): CharacterDetail =
      new CharacterDetail(c.name, c.nicknames, c.origin, c.role, ZIO.effect({
        println(s"calculating statistics for ${c.name}")
        c.nicknames.length
      }))
  }

  case class Queries(
    @GQLDescription("Return all characters from a given origin")
    characters: CharactersArgs => URIO[Console, List[Character]],
    @GQLDeprecated("Use `characters`")
    character: CharacterArgs => URIO[Console, Option[CharacterDetail]],
  )
```
What is the proper way to model it? Is this a good start? And how to write `character` function?

**Comment by ghostdogpr** [comment]
@fokot this is a good start. If you use a `Task` instead of an `Int`, the statistics will be calculated only if the field is requested. If the statistics calculation doesn't require any effect, you can do even simpler and use a function from Unit to Int: `statistics: () => Int`. This will also be executed only when the field is requested.

The `character` function would be similar to the existing one, except you map the result (`Character`) to your type (`CharacterDetail`): 
```scala
args => service.findCharacter(args.name).map(_.map(CharacterDetail(_)))
```

**Comment by fokot** [comment]
Ok this works quite well, thanks 👍 

I'm having another question with same example but I will make another issue as question is not the same.
