### ISSUE TITLE
Improve performance of queries with effectful fields

### ISSUE THREAD

**Issue by andrewpaprotsky** [ghostdogpr/caliban#577]
There appears to be a significant performance penalty if a query requests effectful fields:

```scala
case class Character(
  name: String,
  nameZIO: ZIO[Any, Nothing, String],
  nameZQuery: ZQuery[Any, Nothing, String]
)

case class Query(characters: UIO[List[Character]])

val characters = List(
  Character("James Holden", ZIO.succeed("James Holden"), ZQuery.succeed("James Holden")),
  ...
)
```

```
query simpleQuery {
  characters {
    name
  }
}

query simpleQueryWithZIOField {
  characters {
    nameZIO
  }
}

query simpleQueryWithZQueryField {
  characters {
    nameZQuery
  }
}
```

```
10 items

Benchmark                                            Mode  Cnt      Score      Error  Units
GraphQLBenchmarks.simpleCaliban                     thrpt    5  20533.411 ± 1048.167  ops/s
GraphQLBenchmarks.simpleCalibanWithZIOField         thrpt    5   4834.586 ±  179.417  ops/s
GraphQLBenchmarks.simpleCalibanWithZQueryField      thrpt    5   4850.016 ± 1333.628  ops/s
```

```
1k items

Benchmark                                            Mode  Cnt      Score      Error  Units
GraphQLBenchmarks.simpleCaliban1k                   thrpt    5    647.644 ±    7.786  ops/s
GraphQLBenchmarks.simpleCalibanWithZIOField1k       thrpt    5     56.768 ±    1.141  ops/s
GraphQLBenchmarks.simpleCalibanWithZQueryField1k    thrpt    5     61.713 ±    5.319  ops/s
```

```
10k items

Benchmark                                            Mode  Cnt      Score      Error  Units
GraphQLBenchmarks.simpleCaliban10k                  thrpt    5     69.501 ±    1.087  ops/s
GraphQLBenchmarks.simpleCalibanWithZIOField10k      thrpt    5      6.013 ±    0.136  ops/s
GraphQLBenchmarks.simpleCalibanWithZQueryField10k   thrpt    5      5.744 ±    0.107  ops/s
```

```
100k items

Benchmark                                            Mode  Cnt      Score      Error  Units
GraphQLBenchmarks.simpleCaliban100k                 thrpt    5      6.693 ±    0.144  ops/s
GraphQLBenchmarks.simpleCalibanWithZIOField100k     thrpt    5      0.507 ±    0.034  ops/s
GraphQLBenchmarks.simpleCalibanWithZQueryField100k  thrpt    5      0.533 ±    0.091  ops/s
```

If I disable parallelism for queries (`allowParallelism = false`), the performance of effectful fields improves, making them only 2 times slower than non-effectful ones. I think it's somehow related to `ZQuery.collectAllPar ==> ZQuery.zipWithPar ==> ZIO.zipWithPar` but I can't pin it down. Any pointers are welcome!

**Comment by adamgfraser** [comment]
@andrewpaprotsky Thanks for reporting! Will try to dig into this from the `ZQuery` side. Can you share the code you used for your benchmarks?

**Comment by andrewpaprotsky** [comment]
@adamgfraser Thanks for the prompt reply! The benchmarks are here https://github.com/andrewpaprotsky/caliban/commit/ecc3c3346862e5bf3ee027f8a89fcac398b944af.

**Comment by ghostdogpr** [comment]
I am not surprised that pure fields are much faster because I do some very efficient optimizations in this case: https://github.com/ghostdogpr/caliban/blob/93828521043bf0381b8d606fe46b12940c1d9da1/core/src/main/scala/caliban/execution/Executor.scala#L234 (basically making the cost of executing the whole query down to zero).

The difference of parallelism is concerning though, because we would expect no difference when querying a single field.

**Comment by adamgfraser** [comment]
@ghostdogpr Aren't we not just doing a single query though?

If I add a debug statement in `loop` in `Executor` it looks like if the fields are effectual then we are actually doing one query for each value in the underlying data in `case ReduceStep.ListStep` even if we are only querying a single field. So in the benchmark when the fields are effectual we are either doing `ZQuery.collectAll` with a list of ten elements or `ZQuery.collectAllPar` with a list of ten elements. I'm sure we can do optimizations but I would expect those to have significantly different performance characteristics given that we have to fork ten new fibers in one case but not the other, especially when the data is just sitting there so we aren't getting any benefit in terms of parallelism to offset the overhead of forking those fibers .

**Comment by ghostdogpr** [comment]
@adamgfraser you're right, I didn't realize it was a list and not a single element.

**Comment by ghostdogpr** [comment]
@adamgfraser wow, I tried your improvements on zio-query with the regular benchmarks and it brings a nice x2 improvement on the "simple" scenario, making Caliban more than 4x better than Sangria in all scenarios:

Before:
```
[info] Benchmark                             Mode  Cnt      Score     Error  Units
[info] GraphQLBenchmarks.introspectCaliban  thrpt    5   1876.915 ±  67.937  ops/s
[info] GraphQLBenchmarks.introspectSangria  thrpt    5    451.565 ±   9.993  ops/s
[info] GraphQLBenchmarks.simpleCaliban      thrpt    5  15850.430 ± 246.183  ops/s
[info] GraphQLBenchmarks.simpleSangria      thrpt    5   7267.926 ±  84.398  ops/s
```

After:
```
[info] Benchmark                             Mode  Cnt      Score      Error  Units
[info] GraphQLBenchmarks.introspectCaliban  thrpt    5   1865.875 ±   28.391  ops/s
[info] GraphQLBenchmarks.introspectSangria  thrpt    5    428.303 ±  160.906  ops/s
[info] GraphQLBenchmarks.simpleCaliban      thrpt    5  30620.395 ± 3142.414  ops/s
[info] GraphQLBenchmarks.simpleSangria      thrpt    5   7297.472 ±  212.627  ops/s
```

Could you cut a release with it?

**Comment by adamgfraser** [comment]
@ghostdogpr Will do!

**Comment by ghostdogpr** [comment]
I'm going to close this since I don't see any more action items. The differences can be explain as follows:
- optimizations during the execution phase reduce the cost of a tree of pure resolvers to a single effect which is extremely fast (close to zero cost)
- effectful resolvers on the other hand need to be executed separately, explaining the cost difference. Parallelism makes it worse because creating fibers that don't do anything is not efficient. But in practice effectful resolvers should be doing something real so the time spent creating the fiber will be negligible. 

I am going to release a new version including the ZQuery improvements this weekend.

**Comment by andrewpaprotsky** [comment]
I've added some benchmarks https://github.com/andrewpaprotsky/caliban/commit/b5c8587837f2bf94e8994e47c3a187baa7824740 for complex queries and it looks like sangria is faster with those:

```
[info] Benchmark                                            Mode  Cnt      Score     Error  Units
[info] GraphQLBenchmarks.complexCaliban                    thrpt    5     64.720 ±   0.656  ops/s
[info] GraphQLBenchmarks.complexSangria                    thrpt    5    119.450 ±   1.552  ops/s
```

Again, if I disable parallelism, it gets about 10 times faster. Not sure what's going on there.

**Comment by ghostdogpr** [comment]
Interesting, thanks. I will have a closer look. Reopening the issue.

**Comment by ghostdogpr** [comment]
I did some profiling on this case, all I could see was time spent managing fibers. I think this is due to `ZQuery` creating a fiber for each individual query. The example has 1,000 requests and the `run` execution itself seems pretty fast in comparison with the time managing the 1,000 fibers.

@adamgfraser any idea about this?

<img width="1337" alt="Screen Shot 2020-09-16 at 10 08 04 AM" src="https://user-images.githubusercontent.com/7413894/93280404-85688a80-f804-11ea-90e0-cfd1c8856bf0.png">

**Comment by adamgfraser** [comment]
I think the issue basically comes down to [this](https://github.com/zio/zio-query/blob/e3452ec3f907e1a6f683becd8445b6ec44d58853/zio-query/shared/src/main/scala/zio/query/ZQuery.scala#L371) line. Conceptually we have two potentially distinct types of parallelism:

1. We want to execute requests by data sources in parallel, in which case we just capture the requests as a parallel data type
2. We want to perform arbitrary effects embedded in `ZQuery` in parallel, in which case we actually need to fork fibers

Right now we are combining these, so `zipWithPar` both indicates requests can be performed in parallel and forks fibers, and `zipWith` performs effects sequentially and doesn't fork fibers.

I think ideally we would like the `ZQuery` data type to be rich enough that it can "know" whether the left and right queries potentially perform arbitrary effects. Then if both sides potentially perform arbitrary effects we fork fibers, but otherwise we don't.

I need to think a bit about how to actually implement this but I am on it.

**Comment by ghostdogpr** [comment]
> Again, if I disable parallelism, it gets about 10 times faster. Not sure what's going on there.

Actually this is not right. There is an initialization issue in `ComplexData.scala` that produces a `NullPointerException` when you disable parallelism. If you move `BazDataSource` above `val Bazs`, the error disappears and the results are actually slower without parallelism, which makes sense.

**Comment by ghostdogpr** [comment]
So I'm gonna close this one since there is nothing weird going in with parallelization. The fact that Caliban is slightly slower than Sangria in that particular scenario is acceptable to me, since the time we are measuring here will be quite meaningless in presence of an actual query to some backend.

**Comment by andrewpaprotsky** [comment]
> > Again, if I disable parallelism, it gets about 10 times faster. Not sure what's going on there.
> 
> Actually this is not right. There is an initialization issue in `ComplexData.scala` that produces a `NullPointerException` when you disable parallelism. If you move `BazDataSource` above `val Bazs`, the error disappears and the results are actually slower without parallelism, which makes sense.

Hmmm, I don't see the exception. Maybe something is misconfigured on my side. If I disable parallelism like [this](https://github.com/andrewpaprotsky/caliban/commit/603f0f4fad5b5b2f97276b6f304ce5a3eee8bdc2), Caliban's performance with the complex data improves dramatically:

```
val allowParallelism = false

[info] Benchmark                          Mode  Cnt    Score   Error  Units
[info] GraphQLBenchmarks.complexCaliban  thrpt    5  682.980 ± 9.746  ops/s
[info] GraphQLBenchmarks.complexSangria  thrpt    5  124.128 ± 1.633  ops/s
```

```
val allowParallelism = true

[info] Benchmark                          Mode  Cnt    Score    Error  Units
[info] GraphQLBenchmarks.complexCaliban  thrpt    5   65.773 ±  1.359  ops/s
[info] GraphQLBenchmarks.complexSangria  thrpt    5  118.726 ± 24.946  ops/s
```

**Comment by ghostdogpr** [comment]
Try calling `queryCaliban(complexQuery, complexInterpreter)` in a regular program and print the response, you will see that there's an error.

When `val Bars` is declared, it calls `baz`, which itself calls `BazDataSource`, but `BazDataSource` hasn't been created yet and is null. That's why moving it up solves that error.

**Comment by andrewpaprotsky** [comment]
Oh, my bad, I should have tested the data source before creating the benchmark 🤦‍♂️. Fixing the data source does clear things up. Thanks!
