### ISSUE TITLE
ArgBuilder should return ParsingError when sth goes wrong

### ISSUE THREAD

**Issue by ghostbuster91** [ghostdogpr/caliban#656]
When flat mapping on argBuilders one have to return `ExecutionError` when something goes wrong. Wouldn't be more suitable to return `ParsingError` instead?

**Comment by ghostdogpr** [comment]
Currently it returns `ExecutionError` because it is evaluated during the execution phase.

There are 3 phases:
- parsing turns the query string into an AST
- validation verifies a number of rules
- execution resolves the query

In theory, I think this belongs to the validation phase, because there is a rule [Values of Correct Type](http://spec.graphql.org/June2018/#sec-Values-of-Correct-Type) that checks if the input value can be coerced to the expected type. But this is one of the [few rules](https://github.com/ghostdogpr/caliban/issues/7) that is not implemented yet. Once we implement this rule, I think it will make sense to change it to `ValidationError` but for now I think it should reflect the phase where it is run.

**Comment by ghostbuster91** [comment]
> but for now I think it should reflect the phase where it is run.

Seems reasonable.

> Once we implement this rule, I think it will make sense to change it to ValidationError

Awesome, anything other than ExecutionError will do the work for me. I just want to have clear separation between data level errors and execution errors.

**Comment by ghostdogpr** [comment]
I'll close this and add a note in #656 to make sure this is not missed.
