### ISSUE TITLE
Document how to create custom type from existing case class schema

### ISSUE THREAD

**Issue by maxhillaert** [ghostdogpr/caliban#762]
Hi

The documentation shows how to create a custom type starting with an existing schema for String. 

I have a case class that I want its schema to contain a computed def value. 

It's not clear to me how I can do this. I don't want to create a Schema from scratch as the case class is not small. 

I thought I'd be able to infer a Schema from my Foo case class , then add some fields to it. 

For the life of me I don't know how to do it. 

Some documentation around this, if it is possible to do what I want to do , would be helpful. 

Thanks!

**Comment by ghostdogpr** [comment]
Actually there is no easy way to do that, because a schema can be many different things and no function would work in all cases. But if you know your type is an object type, you can do something similar to contramap (https://github.com/ghostdogpr/caliban/blob/master/core/src/main/scala/caliban/schema/Schema.scala#L83) and add manually your extra field in `__Type` and `Step` (that would be an `ObjectStep`).

In case this is easier, manual creation was made easy recently: https://ghostdogpr.github.io/caliban/docs/schema.html#building-schemas-by-hand (not released yet but will be soon, already available in the latest snapshot).

**Comment by maxhillaert** [comment]
My eyes are bleeding, but this worked :) 

```

  val orig : Schema[Any, AdoPipeline]= Schema.gen[AdoPipeline]

  implicit val s: Schema[Any, AdoPipeline] =  new Schema[Any,AdoPipeline] {
    override def toType(isInput: Boolean): __Type = {
      val t = orig.toType(isInput)
      val foo: __Field = __Field("computedValue", None, List.empty, () => Types.string)
      Types.makeObject(
        t.name,
        t.description,
        t.fields(__DeprecatedArgs()).get :+ foo,
        t.directives.getOrElse(List.empty)
      )
    }

    override def resolve(value: AdoPipeline): Step[Any] = {
      val x = orig.resolve(value)
      val value1 = x.asInstanceOf[ObjectStep[Any]]
      value1.copy(fields = value1.fields + ("computedValue" -> PureStep(StringValue(value.configId))))

    }
  }
```

**Comment by ghostdogpr** [comment]
Yeah that's the idea more or less. You can pattern match on `x` to avoid the ugly `asInstanceOf` 😄 
```scala
orig.resolve(value) match {
  case value1: ObjectStep =>
    value1.copy(fields = value1.fields + ("computedValue" -> PureStep(StringValue(value.configId))))
  case other => other
}
```
