### ISSUE TITLE
Name of input type is always have the suffix "Input"

### ISSUE THREAD

**Issue by nhatnambui** [ghostdogpr/caliban#80]
It's because of this line of code https://github.com/ghostdogpr/caliban/blob/220cf74931589d099c7e254dda63e78db5927b9c/core/src/main/scala/caliban/schema/Types.scala#L41

When generating input type from case class, case object..., the suffix "Input" is always added. Can we avoid that?

**Comment by ghostdogpr** [comment]
@nhatnambui that's because GraphQL requires 2 different types if you have the same type used for input and output. 

Let's say you have the following case class used for input and output:
```scala
case class MyClass(value: Int)
```

Without this "trick", it will generate the following GraphQL types:
```graphql
type MyClass {
  value: Int
}

input MyClass {
  value: Int
}
```

As you can guess, you can't have 2 different types with the same name, that's why I added this prefix. 
So it'll create this:
```graphql
type MyClass {
  value: Int
}

input MyClassInput {
  value: Int
}
```

Any better idea how to handle this?

**Comment by nhatnambui** [comment]
I think it would be better to let user of library define the name explicitly.  Can we achieve that using the annotation?

Or at least in case that the case class is used only for input, the suffix shouldn't be added

**Comment by ghostdogpr** [comment]
The way the schema is derived, we don’t know if the type may be used somewhere else. 

But an annotation sounds reasonable. That way you can choose your suffix or even no suffix at all (at your own peril).

**Comment by ghostdogpr** [comment]
@nhatnambui Added #88 for this. It lets you customize the default logic (by overriding `customizeInputTypeName`) or an individual type (by using `@GQLInputName` annotation). Looks good?
