### ISSUE TITLE
Allow query analysis before execution

### ISSUE THREAD

**Issue by rtimush** [ghostdogpr/caliban#91]
There are some cases where it would be useful to be able to analyze the query before execution. One of the examples is calculating query complexity ([sangria docs](https://sangria-graphql.org/learn/#query-complexity-analysis)) — for each requested field, we need access to the calculated complexity of child fields, arguments (to take page size into account), and some field metadata. This is very similar to what `caliban.Validator` does, so maybe the part related to query traversal (including dealing with fragments) can be generalized to support this use case too.

**Comment by ghostdogpr** [comment]
@rtimush good idea!

Maybe something similar to the recently added `wrapExecutionWith`, where we would pass a function `Document => IO[E, Document]` that would allow modifying the query and possibly rejecting it. Then we can make some helpers to make the traversal easier e.g. some logic by field, and provide builtin ones like the query complexity.

**Comment by rtimush** [comment]
@ghostdogpr This sounds reasonable. It probably makes sense to pass the `RootType` to this wrapper function as well.

**Comment by ghostdogpr** [comment]
@rtimush 

I'm working on a different encoding for validation rules and I was wondering if the same processor could be re-used for query analysis. One potential difference I see is that for validation, we need the original query with fragments and variables (so that we can validate the appropriate rules). For the query analysis, we might want a simpler structure with just "fields" and fragments already replaced? (it's actually not possible to replace them entirely since some of them depend on the actual type returned by the resolver)

Besides simplifying the code, another advantage of reusing the same structure is that we can do all in one pass (validation + analysis). Otherwise we have a validation pass, a transformation, and finally an analysis pass. The downside is that it might be slightly more complex to do some operations when working with the raw query structure.

What do you think?

**Comment by rtimush** [comment]
Doing all validation/processing in one pass is probably indeed more efficient. Maybe we can hide the complexity of the full data structure by providing some utility functions that wrap such processors simplifying the interface.
