### ISSUE TITLE
Manually defined schema with circular dependencies results in a stack overflow error

### ISSUE THREAD

**Issue by smparsons** [ghostdogpr/caliban#920]
I have the following code:

```
import caliban.{GraphQL, RootResolver}
import caliban.schema.Schema.{field, obj}
import caliban.schema.Schema
import zio.{console}
import zio.Runtime

val zioRuntime: Runtime[zio.ZEnv] = Runtime.default

case class Foo(id: Int) {
  def bar() = Bar(234)
}

case class Bar(id: Int) {
  def foo() = Foo(123)
}

implicit lazy val fooSchema: Schema[Any, Foo] = obj("Foo", None)(
  implicit ft =>
    List(
      field("id")(_.id),
      field("bar")(_.bar)
    )
)

implicit lazy val barSchema: Schema[Any, Bar] = obj("Bar", None)(
  implicit ft =>
    List(
       field("id")(_.id),
       field("foo")(_.foo)
    )
)

case class Queries(foos: Seq[Foo])

val queries: Queries = Queries(Seq(Foo(123)))

val calibanApi: GraphQL[Any] = GraphQL.graphQL(RootResolver(queries))

val query = """
{
  foos {
    id
    bar {
      id
    }
  }
}
"""

zioRuntime.unsafeRun {
  for {
    interpreter <- calibanApi.interpreter
    result <- interpreter.execute(query)
    _ <- console.putStrLn(result.data.toString)
  } yield ()
}
```

You can find the playground here: https://scastie.scala-lang.org/smparsons/NULLlRWqRiWcAexDtWLMsA/29

Running the above code results in a stack overflow error. I do realize this is very similar to this issue: https://github.com/ghostdogpr/caliban/issues/858, however, I was under the impression that I shouldn't have the above problem if I define the schema manually (which is what I think you were trying to convey in <a href="https://ghostdogpr.github.io/caliban/docs/schema.html#building-schemas-by-hand">this part of the documentation</a>). That impression could be wrong though, I wanted to ask to make sure. Is a schema with circular dependencies like the above not going to work, even if I define the schema manually?

The problem indeed goes away if I remove `implicit lazy` from `barSchema`, which is fine. But then if I decide to add a `bars: Seq[Bar]` definition to the `Queries` case class, the query `{ bars { id foo { id }  } }` would fail with the error: `Field 'foo' does not exist on type 'Bar'.`

I'm fairly new to Scala, Caliban, and GraphQL in general, so please let me know if I'm doing anything wrong or if I'm not understanding something.

**Comment by ghostdogpr** [comment]
The problem in your example is not actually related to derivation. When we build the whole schema, Caliban generates an "execution plan" which is a tree of `Step` objects representing the root resolver. When an effect or a function is involved, they need to be executed to give you the next steps. In your example though, `bar` and `foo` are declared as simple "values" so their steps are pre-calculated, leading to an infinite tree.

The solution is to make them lazy, by turning it into an effect or a function, like this:
```scala
field("bar")(a => () => a.bar())
field("foo")(a => () => a.foo())
```
That way, those 2 fields will be built dynamically rather than pre-built.
Note that you don't even need the `lazy` before `val`.

We could potentially make that behavior the default when you use `field` so that you don't need to do it, but that would slow down the case where it is an actual value that can be pre-computed (by changing `(v: V) => fn(v).fold(ev.resolve, identity)` to `(v: V) => FunctionStep(_ => fn(v).fold(ev.resolve, identity))`. Or maybe we could add a variant `fieldLazy` that does that. @paulpdaniels thoughts?

**Comment by smparsons** [comment]
Thank you, that fixed the problem. Would it be worth mentioning this in the documentation to help other developers who might run into the same issue I did?

**Comment by ghostdogpr** [comment]
I opened https://github.com/ghostdogpr/caliban/pull/921 to close this issue.
